# Generated by Django 2.1.5 on 2019-01-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sheets', '0002_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='role',
            name='role_name',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Administrator'), (2, 'Student'), (3, 'Teacher')], default=0),
        ),
    ]
